import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
	CARD_APPLICANTS_CLASSES,
	CARD_CLASSES,
	CARD_DESC_CLASSES,
	CARD_MATCH_LABEL_CLASSES,
	CARD_MATCH_VALUE_CLASSES,
	CARD_META_CLASSES,
	CARD_SALARY_CLASSES,
	CARD_SALARY_SUFFIX_CLASSES,
	CARD_SUBTITLE_CLASSES,
	CARD_TAG_CLASSES,
	CARD_TITLE_CLASSES,
	IMAGE_AUTHOR_CLASSES,
	IMAGE_BADGE_CLASSES,
	IMAGE_BODY_CLASSES,
	IMAGE_CARD_CLASSES,
	IMAGE_COVER_CLASSES,
	IMAGE_DATE_CLASSES,
	IMAGE_DESC_CLASSES,
	IMAGE_FOOTER_CLASSES,
	IMAGE_TITLE_CLASSES,
	LOGIN_BUTTON_CLASSES,
	LOGIN_CARD_CLASSES,
	LOGIN_FOOTER_CLASSES,
	LOGIN_LABEL_CLASSES,
	LOGIN_LINK_CLASSES,
	LOGIN_LOGO_CLASSES,
	LOGIN_SUBTITLE_CLASSES,
	LOGIN_TITLE_CLASSES,
	SCHEDULED_CARD_CLASSES,
	SCHEDULED_FOOTER_BUTTON_CLASSES,
	SCHEDULED_ROW_CLASSES,
	SCHEDULED_ROW_META_CLASSES,
	SCHEDULED_ROW_NAME_CLASSES,
	SCHEDULED_STATUS_ACTIVE_CLASSES,
	SCHEDULED_STATUS_IDLE_CLASSES,
	SCHEDULED_SUBTITLE_CLASSES,
	SCHEDULED_TITLE_CLASSES,
} from "./meta";

const tsx = readFileSync(join(__dirname, "card.tsx"), "utf8");

function extractClasses(source: string, name: string): string {
	const pattern = new RegExp(`${name}\\s*=\\s*(?:"([^"]*)"|'([^']*)'|\`([^\`]*)\`)`);
	const match = source.match(pattern);
	if (!match) throw new Error(`Cannot find ${name} in card.tsx`);
	return (match[1] ?? match[2] ?? match[3] ?? "").replace(/\s+/g, " ").trim();
}

const pairs: [string, string][] = [
	["CARD_CLASSES", CARD_CLASSES],
	["META_CLASSES", CARD_META_CLASSES],
	["TITLE_CLASSES", CARD_TITLE_CLASSES],
	["SUBTITLE_CLASSES", CARD_SUBTITLE_CLASSES],
	["DESC_CLASSES", CARD_DESC_CLASSES],
	["TAG_CLASSES", CARD_TAG_CLASSES],
	["SALARY_CLASSES", CARD_SALARY_CLASSES],
	["SALARY_SUFFIX_CLASSES", CARD_SALARY_SUFFIX_CLASSES],
	["APPLICANTS_CLASSES", CARD_APPLICANTS_CLASSES],
	["MATCH_VALUE_CLASSES", CARD_MATCH_VALUE_CLASSES],
	["MATCH_LABEL_CLASSES", CARD_MATCH_LABEL_CLASSES],
	["LOGIN_CARD_CLASSES", LOGIN_CARD_CLASSES],
	["LOGIN_LOGO_CLASSES", LOGIN_LOGO_CLASSES],
	["LOGIN_TITLE_CLASSES", LOGIN_TITLE_CLASSES],
	["LOGIN_SUBTITLE_CLASSES", LOGIN_SUBTITLE_CLASSES],
	["LOGIN_LABEL_CLASSES", LOGIN_LABEL_CLASSES],
	["LOGIN_BUTTON_CLASSES", LOGIN_BUTTON_CLASSES],
	["LOGIN_FOOTER_CLASSES", LOGIN_FOOTER_CLASSES],
	["LOGIN_LINK_CLASSES", LOGIN_LINK_CLASSES],
	["IMAGE_CARD_CLASSES", IMAGE_CARD_CLASSES],
	["IMAGE_COVER_CLASSES", IMAGE_COVER_CLASSES],
	["IMAGE_BODY_CLASSES", IMAGE_BODY_CLASSES],
	["IMAGE_BADGE_CLASSES", IMAGE_BADGE_CLASSES],
	["IMAGE_TITLE_CLASSES", IMAGE_TITLE_CLASSES],
	["IMAGE_DESC_CLASSES", IMAGE_DESC_CLASSES],
	["IMAGE_FOOTER_CLASSES", IMAGE_FOOTER_CLASSES],
	["IMAGE_AUTHOR_CLASSES", IMAGE_AUTHOR_CLASSES],
	["IMAGE_DATE_CLASSES", IMAGE_DATE_CLASSES],
	["SCHEDULED_CARD_CLASSES", SCHEDULED_CARD_CLASSES],
	["SCHEDULED_TITLE_CLASSES", SCHEDULED_TITLE_CLASSES],
	["SCHEDULED_SUBTITLE_CLASSES", SCHEDULED_SUBTITLE_CLASSES],
	["SCHEDULED_ROW_CLASSES", SCHEDULED_ROW_CLASSES],
	["SCHEDULED_ROW_NAME_CLASSES", SCHEDULED_ROW_NAME_CLASSES],
	["SCHEDULED_ROW_META_CLASSES", SCHEDULED_ROW_META_CLASSES],
	["SCHEDULED_STATUS_ACTIVE_CLASSES", SCHEDULED_STATUS_ACTIVE_CLASSES],
	["SCHEDULED_STATUS_IDLE_CLASSES", SCHEDULED_STATUS_IDLE_CLASSES],
	["SCHEDULED_FOOTER_BUTTON_CLASSES", SCHEDULED_FOOTER_BUTTON_CLASSES],
];

describe("card registry mirror", () => {
	it("keeps meta.ts in sync with card.tsx class maps", () => {
		for (const [name, classes] of pairs) {
			expect(classes.replace(/\s+/g, " ").trim(), `${name} drifted`).toBe(extractClasses(tsx, name));
		}
	});
});
